Adding needed configurations

diff --git a/charts/app/templates/grafana.yaml b/charts/app/templates/grafana.yaml
--- a/charts/app/templates/grafana.yaml
+++ b/charts/app/templates/grafana.yaml
@@ -25,29 +25,62 @@ spec:
             - name: GF_SECURITY_ADMIN_PASSWORD
               value: {{ .Values.grafana.gFSecurityAdminPassword }}
           volumeMounts:
-            # - name: grafana-storage
-            #   mountPath: {{ .Values.grafana.mountPaths.storage }}
+            - name: grafana-storage
+              mountPath: {{ .Values.grafana.mountPaths.storage }}
             - name: grafana-datasource
               mountPath: {{ .Values.grafana.mountPaths.datasource }}
             - name: grafana-config
               mountPath: {{ .Values.grafana.mountPaths.config }}
-            - name: grafana-dashboard-providers
-              mountPath: {{ .Values.grafana.mountPaths.dashboardProviders }}
+            # - name: grafana-dashboard-providers
+            #   mountPath: {{ .Values.grafana.mountPaths.dashboardProviders }}
             - name: grafana-dashboards
               mountPath: {{ .Values.grafana.mountPaths.dashboards }} # dashboard JSON files will be placed here
+        # - name: grafana-dashboards-importer
+        #   image: alpine:3.20
+        #   command:
+        #     - /bin/sh
+        #     - -c
+        #     - |
+        #       set -euo pipefail
+        #       echo "Installing dependencies..."
+        #       apk add --no-cache curl jq
+
+        #       for file in {{ .Values.grafana.mountPaths.dashboards }}/*.json; do
+        #         echo "Importing $file"
+        #         if [ ! -s "$file" ]; then
+        #           echo "Skipping empty file $file"
+        #           continue
+        #         fi
+        #         DASHBOARD=$(jq -c . < "$file" || true)
+        #         if [ -z "$DASHBOARD" ]; then
+        #           echo "Failed to parse $file"
+        #           continue
+        #         fi
+        #         echo "Dashboard content: $DASHBOARD"
+        #         curl -s -X POST http://{{ .Values.grafana.gFSecurityAdminUser }}:{{ .Values.grafana.gFSecurityAdminPassword }}@localhost:3000/api/dashboards/db \
+        #           -H "Content-Type: application/json" \
+        #           -d "{\"dashboard\": $DASHBOARD, \"overwrite\": true}" \
+        #           && echo "\nImported $file" \
+        #           || echo "\nFailed to import $file"
+        #       done
+        #       echo "All dashboards processed. Exiting cleanly."
+        #       exit 0
+        #   volumeMounts:
+        #     - name: grafana-dashboards
+        #       mountPath: /tmp/dashboards
       volumes:
-        # - name: grafana-storage
-        #   configMap:
-        #     name: grafana-storage
+        - name: grafana-storage
+          persistentVolumeClaim:
+            claimName: grafana-pvc-storage
         - name: grafana-datasource
           configMap:
             name: grafana-datasource
         - name: grafana-config
           configMap:
             name: grafana-config
-        - name: grafana-dashboard-providers
-          configMap:
-            name: grafana-dashboard-providers
+        # - name: grafana-dashboard-providers
+        #   configMap:
+        #     name: grafana-dashboard-providers
         - name: grafana-dashboards
           configMap:
             name: grafana-dashboards
@@ -66,3 +99,52 @@ spec:
       nodePort: {{ .Values.grafana.service.nodePort }}
   selector:
     app: {{ .Values.grafana.service.name }}
+---
+apiVersion: batch/v1
+kind: Job
+metadata:
+  name: grafana-dashboards-importer
+spec:
+  backoffLimit: 2
+  ttlSecondsAfterFinished: 100
+  template:
+    spec:
+      restartPolicy: Never
+      containers:
+        - name: grafana-dashboards-importer
+          image: alpine:3.20
+          command:
+            - /bin/sh
+            - -c
+            - |
+              set -euo pipefail
+              echo "Installing dependencies..."
+              apk add --no-cache curl jq
+
+              for file in {{ .Values.grafana.mountPaths.dashboards }}/*.json; do
+                echo "Importing $file"
+                if [ ! -s "$file" ]; then
+                  echo "Skipping empty file $file"
+                  continue
+                fi
+                DASHBOARD=$(jq -c . < "$file" || true)
+                if [ -z "$DASHBOARD" ]; then
+                  echo "Failed to parse $file"
+                  continue
+                fi
+                echo "Dashboard content: $DASHBOARD"
+                curl -s -X POST http://{{ .Values.grafana.gFSecurityAdminUser }}:{{ .Values.grafana.gFSecurityAdminPassword }}@{{ .Values.grafana.service.name }}:{{ .Values.grafana.service.port }}/api/dashboards/db \
+                  -H "Content-Type: application/json" \
+                  -d "{\"dashboard\": $DASHBOARD, \"overwrite\": true}" \
+                  && echo "\nImported $file" \
+                  || echo "\nFailed to import $file"
+              done
+              echo "All dashboards processed. Exiting cleanly."
+              exit 0
+          volumeMounts:
+            - name: grafana-dashboards
+              mountPath: {{ .Values.grafana.mountPaths.dashboards }}
+      volumes:
+        - name: grafana-dashboards
+          configMap:
+            name: grafana-dashboards
